# Generated by Django 3.1 on 2020-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200413_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
